import { and, eq, inArray, isNull } from "drizzle-orm";
import type { DrizzleD1Database } from "drizzle-orm/d1";
import getDbClient from "@/db/dbClient";
import { mediaObjects } from "@/db/tables";
import * as Schemas from "@app/schemas";
import AppLogger from "@/providers/logger";
import Utility from "@/utils/Utility";

export default class MediaDAL {
  private db: DrizzleD1Database;

  constructor(env: Env) {
    this.db = getDbClient(env);
  }

  // DEV_NOTE: the publicId is generated by the caller, not here — MediaRepo needs it before this
  // row exists, because it is also the R2 key, and the object is written before the row so a
  // failed upload can never leave a row pointing at bytes that aren't there.
  async createMedia(params: Schemas.CreateMediaDALRequest) {
    const response: Schemas.ApiResponse & { media?: Schemas.Media } = { isSuccess: false };

    try {
      const now = new Date();
      const mediaResponse = await this.db
        .insert(mediaObjects)
        .values({
          publicId: params.publicId,
          userId: params.userId,
          r2Key: params.r2Key,
          contentType: params.contentType,
          bytes: params.bytes,
          width: params.width,
          height: params.height,
          createdAt: now,
          updatedAt: null,
        })
        .returning()
        .get();

      response.isSuccess = true;
      response.message = "Media created successfully";
      response.media = mediaResponse;
    } catch (error) {
      const message = "Unknown error in creating media";
      AppLogger.error({
        category: Schemas.LogCategory.DAL,
        action: Schemas.LogAction.UploadMedia,
        message,
        error,
        metadata: { userId: params.userId, r2Key: params.r2Key },
      });
      response.message = message;
    }

    return response;
  }

  // DEV_NOTE: no userId filter — this backs the unauthenticated GET /media/:publicId, where the
  // unguessable publicId is the credential. The row is still the gate: an id that doesn't resolve
  // to a live row serves nothing, so a soft-deleted object stops being reachable immediately.
  async getMedia(params: Schemas.FindMediaDALRequest) {
    const response: Schemas.ApiResponse & { media?: Schemas.Media | null } = { isSuccess: false };

    try {
      const [media] = await this.db
        .select()
        .from(mediaObjects)
        .where(and(eq(mediaObjects.publicId, params.publicId), isNull(mediaObjects.deletedAt)))
        .limit(1);

      response.isSuccess = true;
      response.message = "Media fetched successfully";
      response.media = media ?? null;
    } catch (error) {
      const message = "Unknown error in fetching media";
      AppLogger.error({
        category: Schemas.LogCategory.DAL,
        action: Schemas.LogAction.GetMedia,
        message,
        error,
        metadata: params,
      });
      response.message = message;
    }

    return response;
  }

  // DEV_NOTE: owner-scoped, unlike getMedia — this one backs cleanup, which must never act on a
  // row belonging to someone else even if a document quotes its URL.
  async getMediaByPublicIds(params: Schemas.GetMediaByPublicIdsDALRequest) {
    const response: Schemas.ApiResponse & { media?: Schemas.Media[] } = { isSuccess: false };

    if (params.publicIds.length === 0) {
      response.isSuccess = true;
      response.message = "Media fetched successfully";
      response.media = [];
      return response;
    }

    try {
      // DEV_NOTE: chunked for D1's 100-bound-parameter cap, same as EntitiesDAL.getEntitiesByIds —
      // the list is however many images a document happens to hold.
      const media: Schemas.Media[] = [];
      for (const publicIds of Utility.chunk(params.publicIds)) {
        const rows = await this.db
          .select()
          .from(mediaObjects)
          .where(
            and(
              eq(mediaObjects.userId, params.userId),
              inArray(mediaObjects.publicId, publicIds),
              isNull(mediaObjects.deletedAt),
            ),
          );
        media.push(...rows);
      }

      response.isSuccess = true;
      response.message = "Media fetched successfully";
      response.media = media;
    } catch (error) {
      const message = "Unknown error in listing media";
      AppLogger.error({
        category: Schemas.LogCategory.DAL,
        action: Schemas.LogAction.GetMedia,
        message,
        error,
        metadata: { userId: params.userId, count: params.publicIds.length },
      });
      response.message = message;
    }

    return response;
  }

  // DEV_NOTE: invariant 9 — the row is soft-deleted. The R2 object is deleted for real by
  // MediaRepo, because unreferenced bytes are the whole point of the cleanup; the row stays as the
  // record that the object existed.
  async deleteMedia(params: Schemas.DeleteMediaDALRequest) {
    const response: Schemas.ApiResponse & { deletedCount?: number } = { isSuccess: false };

    if (params.publicIds.length === 0) {
      response.isSuccess = true;
      response.message = "Media deleted successfully";
      response.deletedCount = 0;
      return response;
    }

    try {
      const now = new Date();
      let deletedCount = 0;

      for (const publicIds of Utility.chunk(params.publicIds)) {
        const deleted = await this.db
          .update(mediaObjects)
          .set({ deletedAt: now, updatedAt: now })
          .where(
            and(
              eq(mediaObjects.userId, params.userId),
              inArray(mediaObjects.publicId, publicIds),
              isNull(mediaObjects.deletedAt),
            ),
          )
          .returning();
        deletedCount += deleted.length;
      }

      response.isSuccess = true;
      response.message = "Media deleted successfully";
      response.deletedCount = deletedCount;
    } catch (error) {
      const message = "Unknown error in deleting media";
      AppLogger.error({
        category: Schemas.LogCategory.DAL,
        action: Schemas.LogAction.DeleteMedia,
        message,
        error,
        metadata: { userId: params.userId, count: params.publicIds.length },
      });
      response.message = message;
    }

    return response;
  }
}
